# Generated by Django 4.0.4 on 2022-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'waiting'), (2, 'shipped'), (3, 'arrived')])),
                ('arrival', models.DateField(blank=True, null=True)),
                ('products', models.ManyToManyField(related_name='product_orders', to='category.product')),
            ],
        ),
    ]
