# Generated by Django 4.0.4 on 2022-04-27 17:05

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to=category.models.product_file_handler),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='file',
            field=models.FileField(null=True, upload_to=category.models.sub_product_file_handler),
        ),
    ]
